import './globals.css'

import { Inter } from 'next/font/google'
import Link from 'next/link'
import React from 'react'

import Navbar from '@/components/Navbar'
import RootStore from '@/stores/RootStore'

const inter = Inter({ subsets: ['latin'] })
export const rootStore = new RootStore()

export const metadata = {
  title: { template: '%s | Azaza', default: 'Create Next App' },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col items-center justify-between">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
